### ISSUE TITLE
Лабораторная 4

### ISSUE THREAD

**Issue by readysloth** [PhoenixAnalist/ARh-labs#2]
+ Скажите, а в чем плюсы использования во вставках имен переменных, а не конкретных регистров?
+ Когда стоит использовать volatile ?

**Comment by PhoenixAnalist** [comment]
Плюс использования имëн переменных в том, что мы получаем уровень абстракции над регистрами, что позволяет не заморачиваться с регистрами, платформами и прочим

Volatile стоит использовать, когда в блоке asm находится что-то важно, что нельзя удалить на этапе компиляции благодаря gcc
