### ISSUE TITLE
Лабораторная 5 Вопросы

### ISSUE THREAD

**Issue by readysloth** [PhoenixAnalist/ARh-labs#3]
+ Вы использовали вместо FPU другое расширение процессора, расскажите, что это за расширение :)
+ Какой размер ячейки регистра стека в FPU?

P.S
Я сталкивался в свое время с ошибкой на x86-64 при передаче в функцию `printf` результатов вычисления на FPU , так как пихал в функцию непреобразованный результат.
```asm
   0x00007ffff7e46910 <+0>:     sub    $0xd8,%rsp
   0x00007ffff7e46917 <+7>:     mov    %rdi,%r10
   0x00007ffff7e4691a <+10>:    mov    %rsi,0x28(%rsp)
   0x00007ffff7e4691f <+15>:    mov    %rdx,0x30(%rsp)
   0x00007ffff7e46924 <+20>:    mov    %rcx,0x38(%rsp)
   0x00007ffff7e46929 <+25>:    mov    %r8,0x40(%rsp)
   0x00007ffff7e4692e <+30>:    mov    %r9,0x48(%rsp)
   0x00007ffff7e46933 <+35>:    test   %al,%al
   0x00007ffff7e46935 <+37>:    je     0x7ffff7e4696e <printf+94>
   0x00007ffff7e46937 <+39>:    movaps %xmm0,0x50(%rsp)
   0x00007ffff7e4693c <+44>:    movaps %xmm1,0x60(%rsp)
   0x00007ffff7e46941 <+49>:    movaps %xmm2,0x70(%rsp)
   0x00007ffff7e46946 <+54>:    movaps %xmm3,0x80(%rsp)
   0x00007ffff7e4694e <+62>:    movaps %xmm4,0x90(%rsp)
   0x00007ffff7e46956 <+70>:    movaps %xmm5,0xa0(%rsp)
   0x00007ffff7e4695e <+78>:    movaps %xmm6,0xb0(%rsp)
   0x00007ffff7e46966 <+86>:    movaps %xmm7,0xc0(%rsp)
   0x00007ffff7e4696e <+94>:    mov    %fs:0x28,%rax
   0x00007ffff7e46977 <+103>:   mov    %rax,0x18(%rsp)
   0x00007ffff7e4697c <+108>:   xor    %eax,%eax
   0x00007ffff7e4697e <+110>:   lea    0xe0(%rsp),%rax
```

**Comment by Kate-png** [comment]
1. XMM-расширение. Оно реализовано в виде аппаратно-программного модуля SSE, который включает дополнительные восемь регистров разрядностью в 128 бит, имеющих обозначение ХММО - ХММ7.
SSE включает в архитектуру процессора восемь 128-битных регистров и набор инструкций, работающих со скалярными и упакованными типами данных.

Преимущество в производительности достигается в том случае, когда необходимо произвести одну и ту же последовательность действий над разными данными. В таком случае блоком SSE осуществляется распараллеливание вычислительного процесса между данными.

2. Старший разряд 80-разрядного регистра данных кодирует знак мантиссы хранящегося в нем числа с плавающей точкой. Следующее поле отведено под кодирование порядка. Порядок представлен в виде так называемого машинного, или смещенного, порядка (Псм) без знака:

80 бит
